# Site settings
title: "🇵🇭 Philippine Government Icons"
description: "A comprehensive library of Philippine government icons and symbols for developers"
url: "https://iyanski.github.io"
baseurl: "/better-gov-logos"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections
collections:
  icons:
    output: true
    permalink: /:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "icons"
    values:
      layout: "icon"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - README.md
  - package.json
  - package-lock.json
  - node_modules/
  - tools/
  - packages/
  - .gitignore
  - .github/

# Include
include:
  - _pages

# Navigation
navigation:
  - title: "Home"
    url: "/"
  - title: "Icons"
    url: "/icons/"
  - title: "Installation"
    url: "/installation/"
  - title: "CLI"
    url: "/cli/"
  - title: "Contributing"
    url: "/contributing/"

# Social links
social:
  github: "iyanski/better-gov-logos"
  twitter: "ph_gov_icons"

# Analytics (optional)
# google_analytics: "GA_TRACKING_ID"
